### ISSUE TITLE
comps.dexseq: TypeError from all_pairs.sort

### ISSUE THREAD

**Issue by borshago** [grexor/apa#15]
Hi,

I'm running the apa pipeline from master, using python 3.7.6. I got the following error:

> ...comps/__init__.py", line 1004, in dexseq
>     all_pairs.sort(reverse=True) # just to check, because they are already sorted by highest expression
> TypeError: '<' not supported between instances of 'dict' and 'dict'

A workaround to the error is commenting or removing the line. Just to make sure: the line is unnecessary for the analysis, right?

Best,
Daniel

**Comment by grexor** [comment]
Hi borshago,

sorry for the late reply, will try to be more responsive now :)

Strange, since the all_pairs is a tuple list (should have the expression value as first tuple element) and should work also in Python 3*. Did you solve it? Otherwise removing this line should not change the results...

Hope this helps,
Gregor

**Comment by grexor** [comment]
Using the example this should work now, closing this issue for now. Thanks, Gregor
